"""Added Replay_text column to Ticket model

Revision ID: 2477a0392280
Revises: 0913fd2ca901
Create Date: 2024-11-24 19:40:57.733879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2477a0392280'
down_revision = '0913fd2ca901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('specialization')

    # ### end Alembic commands ###
